### ISSUE TITLE
Please remove SVG check mark icons

### ISSUE THREAD

**Issue by kyoshino** [acalvo/css-compat#1]
Hello,

I’ve just noticed that your repository contains SVG icons which are apparently taken from [my repository](https://github.com/fxsitecompat/firefox-extension). These files are identical:

* https://github.com/fxsitecompat/firefox-extension/blob/master/extension/devtools/icon-check-dark.svg
    * https://github.com/acalvo/css-compat/blob/master/static/images/icon-check-dark.svg

* https://github.com/fxsitecompat/firefox-extension/blob/master/extension/devtools/icon-check-light.svg
    * https://github.com/acalvo/css-compat/blob/master/static/images/icon-check-light.svg

Files in my repository are *not* open source, so please kindly remove them from your work.

Thank you!

**Comment by acalvo** [comment]
Apologies, I took for granted that they had an open license. I should have checked carefully! I've replaced them with [Firefox's Photon icons](https://design.firefox.com/icons/viewer/). Thanks for the report!

**Comment by kyoshino** [comment]
Thanks for the quick turnaround 💯  Good luck with you project!
